for i in **/.git; do ( echo $i; cd $i/..; git pull; ); done
for i in **/.git; do ( echo $i; cd $i/..; git pull; ); done
for i in */.git; do ( echo $i; cd $i/..; git pull; ); done
for i in **/*/.git; do ( echo $i; cd $i/..; git pull; ); done
for i in */.git; do ( echo $i; cd $i/..; git pull; ); done
for i in **/*/.git; do ( echo $i; cd $i/..; git pull; ); done
for i in */.git; do ( echo $i; cd $i/..; git pull; ); done
for i in **/*/.git; do ( echo $i; cd $i/..; git pull; ); done
for i in */.git; do ( echo $i; cd $i/..; git pull; ); done
for i in **/*/.git; do ( echo $i; cd $i/..; git pull; ); done
